use crate::generation::LyricDocId;
use serde::{Deserialize, Serialize};

/// Opaque id for a track. Filesystem-safe and sortable; `library` mints it.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(transparent)]
pub struct TrackId(pub String);

/// Stable id for one generated artwork, e.g. `"ar-0001"`.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(transparent)]
pub struct ArtId(pub String);

/// Where a lyric version came from. Records whether the user accepted an optimised
/// prompt, which must never happen silently (ARCHITECTURE 6).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum LyricSource {
    /// Typed or pasted by the user.
    Human,
    /// Generated by an LLM.
    Llm {
        /// The model that produced the draft.
        model: String,
        /// True only if the user accepted an optimised prompt for this generation.
        #[serde(default)]
        prompt_optimized: bool,
    },
    /// Hand-edited from an earlier version.
    Edited {
        /// The version this edit started from.
        from_version: u32,
    },
}

/// One immutable revision of a lyric document. Versions are whole copies: cheap at
/// this size, and it means an edit can never corrupt the text it came from.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct LyricVersion {
    /// 1-based, monotonically increasing within a document.
    pub number: u32,
    /// The lyric text for this version.
    pub text: String,
    /// RFC 3339, e.g. `"2026-08-23T18:31:24Z"`.
    pub created_at: String,
    /// How this version was produced.
    pub source: LyricSource,
}

/// A set of lyric revisions, one of which may be approved for audio generation.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct LyricDoc {
    /// Document id, minted by `library`.
    pub id: LyricDocId,
    /// Optional user-facing title.
    #[serde(default)]
    pub title: Option<String>,
    /// All versions, oldest to newest.
    pub versions: Vec<LyricVersion>,
    /// `LyricVersion::number` the user approved, if any. Only an approved version can
    /// be sent to AudioStudio.
    #[serde(default)]
    pub approved: Option<u32>,
}

impl LyricDoc {
    /// The approved version, if one has been chosen.
    pub fn approved_version(&self) -> Option<&LyricVersion> {
        let n = self.approved?;
        self.versions.iter().find(|v| v.number == n)
    }

    /// The most recent version by number, if the document has any.
    pub fn latest(&self) -> Option<&LyricVersion> {
        self.versions.iter().max_by_key(|v| v.number)
    }

    /// Appends a version and returns its number.
    ///
    /// Numbers continue from the highest already present, so a restored older
    /// version cannot collide with one that came after it. Existing versions are
    /// never touched -- an edit produces a new version, it does not rewrite the
    /// text it came from.
    pub fn push_version(
        &mut self,
        text: impl Into<String>,
        source: LyricSource,
        created_at: impl Into<String>,
    ) -> u32 {
        let number = self.latest().map_or(1, |v| v.number + 1);
        self.versions.push(LyricVersion {
            number,
            text: text.into(),
            created_at: created_at.into(),
            source,
        });
        number
    }

    /// Approves an existing version, returning `false` and changing nothing when
    /// no version has that number.
    ///
    /// Approval is what makes a version available to AudioStudio, so approving a
    /// number that does not exist must not clear the approval the user already
    /// made.
    pub fn approve(&mut self, number: u32) -> bool {
        if !self.versions.iter().any(|v| v.number == number) {
            return false;
        }
        self.approved = Some(number);
        true
    }
}

/// A named ordering of tracks -- a single, an EP, an album.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct AlbumList {
    /// User-facing name for this list.
    pub name: String,
    /// Tracks in the order the user arranged them.
    #[serde(default)]
    pub tracks: Vec<TrackId>,
    /// The artwork shown for this list, when the user has chosen one.
    ///
    /// An album has no file of its own (T-403), so unlike a track's cover this one
    /// lives in `project.json` with the rest of the list. Same rule otherwise.
    #[serde(default)]
    pub cover: Option<ArtId>,
}

/// A working project. Holds *ids only* for tracks: every fact about a track lives in
/// its sidecar, so a rename cannot leave two files disagreeing (ARCHITECTURE 8).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Project {
    /// Directory name under the app config dir's `projects/`; filesystem-safe.
    pub slug: String,
    /// User-facing project name.
    pub name: String,
    /// RFC 3339.
    pub created_at: String,
    /// Ordered; newest last.
    #[serde(default)]
    pub tracks: Vec<TrackId>,
    /// Artwork generated in this project. Ids only, same rule as `tracks`:
    /// every fact about an artwork lives in its sidecar (ARCHITECTURE 8).
    #[serde(default)]
    pub art: Vec<ArtId>,
    /// Lyric documents belonging to this project.
    #[serde(default)]
    pub lyrics: Vec<LyricDocId>,
    /// Named album lists within this project.
    #[serde(default)]
    pub albums: Vec<AlbumList>,
    /// Sequence number the next lyric document in this project will be minted from.
    ///
    /// Monotonic and **never reused**, even after a document is deleted. Minting from
    /// the surviving file list instead would hand a deleted document's id to a later
    /// one, and a track's provenance `LyricRef` would then point at unrelated lyrics.
    #[serde(default = "default_lyric_seq")]
    pub next_lyric_seq: u32,
    /// Sequence number the next track in this project will be minted from.
    ///
    /// Monotonic and **never reused**, even after a track is deleted. Minting from
    /// the surviving file list instead would hand a deleted track's id to a later
    /// one, and an `AlbumList` still holding the old `TrackId` would then point at
    /// unrelated audio.
    #[serde(default = "default_track_seq")]
    pub next_track_seq: u32,
    /// Sequence number the next artwork in this project will be minted from.
    ///
    /// Monotonic and **never reused**, for the same reason `next_track_seq` is:
    /// a freed id handed to a later artwork would silently re-point whatever
    /// referenced the old one.
    #[serde(default = "default_art_seq")]
    pub next_art_seq: u32,
}

fn default_lyric_seq() -> u32 {
    1
}

fn default_track_seq() -> u32 {
    1
}

fn default_art_seq() -> u32 {
    1
}

impl Project {
    /// A new, empty project. `created_at` is RFC 3339; the caller supplies it so
    /// nothing here reads a clock.
    pub fn new(
        slug: impl Into<String>,
        name: impl Into<String>,
        created_at: impl Into<String>,
    ) -> Self {
        Self {
            slug: slug.into(),
            name: name.into(),
            created_at: created_at.into(),
            tracks: Vec::new(),
            art: Vec::new(),
            lyrics: Vec::new(),
            albums: Vec::new(),
            next_lyric_seq: default_lyric_seq(),
            next_track_seq: default_track_seq(),
            next_art_seq: default_art_seq(),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_approved_version_returns_that_version() {
        let doc = LyricDoc {
            id: LyricDocId("ld-1".to_string()),
            title: None,
            versions: vec![
                LyricVersion {
                    number: 1,
                    text: "first".to_string(),
                    created_at: "2026-08-23T18:00:00Z".to_string(),
                    source: LyricSource::Human,
                },
                LyricVersion {
                    number: 2,
                    text: "second".to_string(),
                    created_at: "2026-08-23T18:31:24Z".to_string(),
                    source: LyricSource::Human,
                },
            ],
            approved: Some(2),
        };
        let v = doc
            .approved_version()
            .expect("should find approved version");
        assert_eq!(v.number, 2);
        assert_eq!(v.text, "second");
    }

    #[test]
    fn test_approved_version_is_none_when_unapproved() {
        let doc = LyricDoc {
            id: LyricDocId("ld-1".to_string()),
            title: None,
            versions: vec![LyricVersion {
                number: 1,
                text: "first".to_string(),
                created_at: "2026-08-23T18:00:00Z".to_string(),
                source: LyricSource::Human,
            }],
            approved: None,
        };
        assert!(doc.approved_version().is_none());
    }

    #[test]
    fn test_latest_returns_highest_numbered_version() {
        let doc = LyricDoc {
            id: LyricDocId("ld-1".to_string()),
            title: None,
            versions: vec![
                LyricVersion {
                    number: 3,
                    text: "third".to_string(),
                    created_at: "2026-08-23T19:00:00Z".to_string(),
                    source: LyricSource::Human,
                },
                LyricVersion {
                    number: 1,
                    text: "first".to_string(),
                    created_at: "2026-08-23T18:00:00Z".to_string(),
                    source: LyricSource::Human,
                },
                LyricVersion {
                    number: 2,
                    text: "second".to_string(),
                    created_at: "2026-08-23T18:30:00Z".to_string(),
                    source: LyricSource::Human,
                },
            ],
            approved: None,
        };
        let latest = doc.latest().expect("should have a latest version");
        assert_eq!(latest.number, 3);
        assert_eq!(latest.text, "third");
    }

    #[test]
    fn test_lyric_source_llm_records_optimized_flag() {
        let original = LyricSource::Llm {
            model: "gemma-4-12b".to_string(),
            prompt_optimized: true,
        };
        let json = serde_json::to_string(&original).unwrap();
        let parsed: LyricSource = serde_json::from_str(&json).unwrap();
        match parsed {
            LyricSource::Llm {
                model,
                prompt_optimized,
            } => {
                assert_eq!(model, "gemma-4-12b");
                assert!(prompt_optimized);
            }
            other => panic!("expected Llm variant, got {:?}", other),
        }
    }

    /// Invariant: a new version continues from the highest number present, so a
    /// document whose latest version is 3 can never mint a second 3.
    #[test]
    fn test_push_version_continues_from_the_highest_number() {
        let mut doc = LyricDoc {
            id: LyricDocId("ld-0001".to_string()),
            title: None,
            versions: Vec::new(),
            approved: None,
        };
        assert_eq!(
            doc.push_version("one", LyricSource::Human, "2026-08-25T10:00:00Z"),
            1
        );
        assert_eq!(
            doc.push_version(
                "two",
                LyricSource::Llm {
                    model: "gemma4:12b-32k".to_string(),
                    prompt_optimized: false,
                },
                "2026-08-25T10:01:00Z",
            ),
            2
        );
        assert_eq!(
            doc.push_version(
                "three",
                LyricSource::Edited { from_version: 1 },
                "2026-08-25T10:02:00Z"
            ),
            3
        );
        assert_eq!(doc.versions.len(), 3);
        assert_eq!(doc.versions[0].text, "one");
    }

    /// Invariant: the next number comes from the highest version present, not
    /// from how many there are. A document that has lost a version -- or that
    /// was written by a build which numbered differently -- must not mint a
    /// number an existing version already holds, because a `LyricRef` in a
    /// track's provenance points at lyrics by number.
    #[test]
    fn test_push_version_after_a_gap_does_not_reuse_a_number() {
        let mut doc = LyricDoc {
            id: LyricDocId("ld-0001".to_string()),
            title: None,
            versions: vec![
                LyricVersion {
                    number: 1,
                    text: "first".to_string(),
                    created_at: "2026-08-25T10:00:00Z".to_string(),
                    source: LyricSource::Human,
                },
                LyricVersion {
                    number: 5,
                    text: "fifth".to_string(),
                    created_at: "2026-08-25T10:05:00Z".to_string(),
                    source: LyricSource::Human,
                },
            ],
            approved: Some(5),
        };
        assert_eq!(
            doc.push_version("next", LyricSource::Human, "2026-08-25T10:06:00Z"),
            6
        );
        let numbers: Vec<u32> = doc.versions.iter().map(|v| v.number).collect();
        assert_eq!(numbers, vec![1, 5, 6]);
    }

    /// Invariant: approving a number that does not exist leaves the approval the
    /// user already made untouched. Clearing it would silently withdraw a lyric
    /// from AudioStudio.
    #[test]
    fn test_approve_missing_version_keeps_the_previous_approval() {
        let mut doc = LyricDoc {
            id: LyricDocId("ld-0001".to_string()),
            title: None,
            versions: Vec::new(),
            approved: None,
        };
        doc.push_version("one", LyricSource::Human, "2026-08-25T10:00:00Z");
        assert!(doc.approve(1));
        assert_eq!(doc.approved, Some(1));

        assert!(!doc.approve(9));
        assert_eq!(doc.approved, Some(1));
    }

    /// Invariant: a project file written before `next_lyric_seq` existed still
    /// loads, and starts minting at 1 rather than 0.
    #[test]
    fn test_project_without_seq_field_defaults_to_one() {
        let json = r#"{"slug":"demo","name":"Demo","created_at":"2026-08-25T10:00:00Z"}"#;
        let project: Project = serde_json::from_str(json).unwrap();
        assert_eq!(project.next_lyric_seq, 1);
        assert!(project.lyrics.is_empty());
    }

    /// Invariant: a project file written before `next_track_seq` existed still
    /// loads, and starts minting at 1 rather than 0.
    #[test]
    fn test_track_seq_defaults_for_a_project_written_before_it_existed() {
        let json = r#"{"slug":"demo","name":"Demo","created_at":"2026-08-25T10:00:00Z"}"#;
        let project: Project = serde_json::from_str(json).unwrap();
        assert_eq!(project.next_track_seq, 1);
        assert!(project.tracks.is_empty());
    }

    /// Invariant: a project file written before artwork existed still loads,
    /// with an empty art list and the counter starting at 1.
    #[test]
    fn test_art_defaults_for_a_project_written_before_it_existed() {
        let json = r#"{"slug":"demo","name":"Demo","created_at":"2026-08-25T10:00:00Z"}"#;
        let project: Project = serde_json::from_str(json).unwrap();
        assert!(project.art.is_empty());
        assert_eq!(project.next_art_seq, 1);
    }

    /// Invariant: an album written before `cover` existed still loads, with
    /// `cover: None`. The key must be stripped to prove `serde(default)`.
    #[test]
    fn test_album_written_before_cover_existed_still_loads() {
        let json = r#"{"name":"Demo","tracks":["tr-0001"]}"#;
        let album: AlbumList = serde_json::from_str(json).unwrap();
        assert_eq!(album.name, "Demo");
        assert_eq!(album.tracks, vec![TrackId("tr-0001".to_string())]);
        assert_eq!(album.cover, None);
    }
}
