use crate::generation::LyricDocId;
use serde::{Deserialize, Serialize};

/// Opaque id for a track. Filesystem-safe and sortable; `library` mints it.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(transparent)]
pub struct TrackId(pub String);

/// Where a lyric version came from. Records whether the user accepted an optimised
/// prompt, which must never happen silently (ARCHITECTURE 6).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum LyricSource {
    /// Typed or pasted by the user.
    Human,
    /// Generated by an LLM.
    Llm {
        /// The model that produced the draft.
        model: String,
        /// True only if the user accepted an optimised prompt for this generation.
        #[serde(default)]
        prompt_optimized: bool,
    },
    /// Hand-edited from an earlier version.
    Edited {
        /// The version this edit started from.
        from_version: u32,
    },
}

/// One immutable revision of a lyric document. Versions are whole copies: cheap at
/// this size, and it means an edit can never corrupt the text it came from.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct LyricVersion {
    /// 1-based, monotonically increasing within a document.
    pub number: u32,
    /// The lyric text for this version.
    pub text: String,
    /// RFC 3339, e.g. `"2026-08-23T18:31:24Z"`.
    pub created_at: String,
    /// How this version was produced.
    pub source: LyricSource,
}

/// A set of lyric revisions, one of which may be approved for audio generation.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct LyricDoc {
    /// Document id, minted by `library`.
    pub id: LyricDocId,
    /// Optional user-facing title.
    #[serde(default)]
    pub title: Option<String>,
    /// All versions, oldest to newest.
    pub versions: Vec<LyricVersion>,
    /// `LyricVersion::number` the user approved, if any. Only an approved version can
    /// be sent to AudioStudio.
    #[serde(default)]
    pub approved: Option<u32>,
}

impl LyricDoc {
    /// The approved version, if one has been chosen.
    pub fn approved_version(&self) -> Option<&LyricVersion> {
        let n = self.approved?;
        self.versions.iter().find(|v| v.number == n)
    }

    /// The most recent version by number, if the document has any.
    pub fn latest(&self) -> Option<&LyricVersion> {
        self.versions.iter().max_by_key(|v| v.number)
    }
}

/// A named ordering of tracks — a single, an EP, an album.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct AlbumList {
    /// User-facing name for this list.
    pub name: String,
    /// Tracks in the order the user arranged them.
    #[serde(default)]
    pub tracks: Vec<TrackId>,
}

/// A working project. Holds *ids only* for tracks: every fact about a track lives in
/// its sidecar, so a rename cannot leave two files disagreeing (ARCHITECTURE 8).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Project {
    /// Directory name under `library/projects/`; filesystem-safe.
    pub slug: String,
    /// User-facing project name.
    pub name: String,
    /// RFC 3339.
    pub created_at: String,
    /// Ordered; newest last.
    #[serde(default)]
    pub tracks: Vec<TrackId>,
    /// Lyric documents belonging to this project.
    #[serde(default)]
    pub lyrics: Vec<LyricDocId>,
    /// Named album lists within this project.
    #[serde(default)]
    pub albums: Vec<AlbumList>,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_approved_version_returns_that_version() {
        let doc = LyricDoc {
            id: LyricDocId("ld-1".to_string()),
            title: None,
            versions: vec![
                LyricVersion {
                    number: 1,
                    text: "first".to_string(),
                    created_at: "2026-08-23T18:00:00Z".to_string(),
                    source: LyricSource::Human,
                },
                LyricVersion {
                    number: 2,
                    text: "second".to_string(),
                    created_at: "2026-08-23T18:31:24Z".to_string(),
                    source: LyricSource::Human,
                },
            ],
            approved: Some(2),
        };
        let v = doc
            .approved_version()
            .expect("should find approved version");
        assert_eq!(v.number, 2);
        assert_eq!(v.text, "second");
    }

    #[test]
    fn test_approved_version_is_none_when_unapproved() {
        let doc = LyricDoc {
            id: LyricDocId("ld-1".to_string()),
            title: None,
            versions: vec![LyricVersion {
                number: 1,
                text: "first".to_string(),
                created_at: "2026-08-23T18:00:00Z".to_string(),
                source: LyricSource::Human,
            }],
            approved: None,
        };
        assert!(doc.approved_version().is_none());
    }

    #[test]
    fn test_latest_returns_highest_numbered_version() {
        let doc = LyricDoc {
            id: LyricDocId("ld-1".to_string()),
            title: None,
            versions: vec![
                LyricVersion {
                    number: 3,
                    text: "third".to_string(),
                    created_at: "2026-08-23T19:00:00Z".to_string(),
                    source: LyricSource::Human,
                },
                LyricVersion {
                    number: 1,
                    text: "first".to_string(),
                    created_at: "2026-08-23T18:00:00Z".to_string(),
                    source: LyricSource::Human,
                },
                LyricVersion {
                    number: 2,
                    text: "second".to_string(),
                    created_at: "2026-08-23T18:30:00Z".to_string(),
                    source: LyricSource::Human,
                },
            ],
            approved: None,
        };
        let latest = doc.latest().expect("should have a latest version");
        assert_eq!(latest.number, 3);
        assert_eq!(latest.text, "third");
    }

    #[test]
    fn test_lyric_source_llm_records_optimized_flag() {
        let original = LyricSource::Llm {
            model: "gemma-4-12b".to_string(),
            prompt_optimized: true,
        };
        let json = serde_json::to_string(&original).unwrap();
        let parsed: LyricSource = serde_json::from_str(&json).unwrap();
        match parsed {
            LyricSource::Llm {
                model,
                prompt_optimized,
            } => {
                assert_eq!(model, "gemma-4-12b");
                assert!(prompt_optimized);
            }
            other => panic!("expected Llm variant, got {:?}", other),
        }
    }
}
